### ISSUE TITLE
 Add INKBIRD IBBQ IBT-2X BBQ temperature sensor

### ISSUE THREAD

**Issue by freddyf** [1technophile/OpenMQTTGateway#1083]
This probe sensor is already recognized but not in the right way.

It is marked as an IBT-4XS with 4 thermometers, but this model has only two.
Anyway, the 2 thermometers works fine labeled using tempc and tempc2

Thank You & great work!

**Comment by 1technophile** [comment]
Thanks, Could you share a screenshot with the manufacturer data of it like in the discussion [here](https://community.openmqttgateway.com/t/ble-wireless-bbq-temperature-probe-with-esp32/1561/14?u=1technophile)

**Comment by freddyf** [comment]
![image](https://user-images.githubusercontent.com/1830630/135710369-c9f295c5-7dd4-4a8f-a883-02f029cc2ae7.png)

here it is.
Thank you again!!

ps: sorry, i'm not able to resize the img...

**Comment by 1technophile** [comment]
@freddyf could you try out this branch please?
https://github.com/1technophile/OpenMQTTGateway/tree/decoder-dev

And see if the model is correctly recognized

**Comment by 1technophile** [comment]
Done

**Comment by SerpikoIT** [comment]
Hello I have the version of OpenMQTTGateway v0.9.10 before I had a version 0.98 and I was using inkbird 2x as well if it saw it as 4x, today I put the latest version the 0.9.10 and I find that instead of seeing it 2x or 4x I am IBEACON Gneric in two different items and I can understand that they are the 2 probes, but does not see the correct name like "inkbird2xs_temp1" why ??? I had read that it was detected automatically

thank you
