### ISSUE TITLE
Puck.JS integration

### ISSUE THREAD

**Issue by hallard** [1technophile/OpenMQTTGateway#1293]
Hi @DigiH 

As asked, just sorted out my puck.js it's an espruino device, and need to be programmed (in js) with an application. 
So what app you want me to try?

There are so [much](https://espruino.github.io/EspruinoApps/) may be `Bluetooth Advertiser - Everything! `

**Comment by hallard** [comment]
Installed `Bluetooth Advertiser - Everything!` app on my puck.js and here are results

Source code of the app is [here](https://github.com/espruino/EspruinoApps/tree/master/apps/bleeverything) it may help for encoding format :-)

```json
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-71,"servicedata":"303030","servicedatauuid":"0x183d"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-43,"servicedata":"00","servicedatauuid":"0x183c"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-77,"servicedata":"4a","servicedatauuid":"0x1809"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-30,"servicedata":"303030","servicedatauuid":"0x183d"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-82,"brand":"GENERIC","model":"Service data","model_id":"ServiceData","batt":100}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-36,"servicedata":"303030","servicedatauuid":"0x183d"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-29,"servicedata":"303030","servicedatauuid":"0x183d"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-77,"servicedata":"302e3234","servicedatauuid":"0x182a"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-28,"servicedata":"303030","servicedatauuid":"0x183d"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 6","rssi":-85,"servicedata":"302e3231303136353032333830","servicedatauuid":"0x182b"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-28,"servicedata":"303030","servicedatauuid":"0x183d"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-81,"servicedata":"303030","servicedatauuid":"0x183d"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-35,"servicedata":"00","servicedatauuid":"0x183c"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-78,"servicedata":"00","servicedatauuid":"0x183c"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-30,"servicedata":"00","servicedatauuid":"0x183c"}
{"id":"FD:52:F6:D9:66:F9","mac_type":1,"name":"Puck.js 66f9","rssi":-80,"servicedata":"00","servicedatauuid":"0x183c"}
```

**Comment by DigiH** [comment]
Thanks @hallard , will have a look at these and the app source. Once we got this **everything** sorted maybe we can look at the others with their individual details, to see if they are just a subset of the encodings, or if they have their own encoding rules.

**Comment by hallard** [comment]
BTW as far as I remember battery life duration is not awesome, but depends a lot of application used and advertisement frequency, I'll see how long this one live.

**Comment by DigiH** [comment]
@hallard Could you use the `esp32dev-ble-datatest` environment/binary again for logging for the Puck.js?

The battery seems to already be recognised by the standard ServiceData decoder, possibly some of the others also follow the Bluetooth SIG service conventions, although `0x1809` (Health Thermometer) with **4a** -> 74º would only make sense if you had the Puck.js set to report in Fahrenheit - or in the oven ;)

Will have to look at the app source though for a better understanding.

**Comment by hallard** [comment]
@DigiH, humm this is the version I build on my Denky board, strange, but got 2 OMG, but one (the production) without dataset may be I subscribed to the wrong one to get logs, I need to check that, thanks for pointing that out

**Comment by DigiH** [comment]
> `0x1809` (Health Thermometer) with **4a** -> 74º

So yes, the **Everything** app broadcasts the temperature in Fahrenheit by default. So that's a first. And only in the **Everything** app, it seems, with the temp only app broadcasting in Celsius - hmm.

And all the others seem pretty clear as well, but would need more testing and logging.

**BTW** do you know which hardware revision of the Puck.js you have?

**Comment by DigiH** [comment]
@hallard - Looking more at the different apps, it seems clear that they are more example apps to follow for creating your own, than ready to go for general use apps. The Fahrenheit temperature broadcast being one example here, also using the Health Thermometer service uuid instead of the Temperature one makes us believe that it is not really worth creating a decoder for what are just example apps.

If you feel like creating a ready for release app to work with the different Puck.js versions, adhering to the standard service uuids, it might be a different case, if you made that publicly available for use by other Puck.js users.

**Comment by bouton** [comment]
Wow this is a lucky coincidence.  I was just looking into OMG for use with my Espruino Puck and Bangle watch.  I AM NOT a bluetooth expert in any way, but was able to program/hack my puck to broadcast on press (using different counts for different advertising) using std bluetooth conventions. ie one puck button press sends 0x2A56 (digital) and two button presses sends 0x2A06 (alert).
Espruino has a javascript hub which runs on a rasp pi zerow which then translates(?) this ble advertising into MQTT with home assistant compatibility, which I can then read and use for automations.  (clear?)  Their [github ](https://github.com/espruino/EspruinoHub) lists all the std code that the espruino hub decodes to mqtt.
The Bangle I have written js code to work as a ibeacon which I use for presence detection, also using the espruino hub ble-mqtt

I wanted to cut down on all the various devices I have scattered around the house, trying to combine them into one. So tried OMG but have stumbled when it comes to all the "decoding". So if this is on your radar great!

Otherwise, is there a way to "decode" std ble sig codes and where would I find out how to do that using OMG is Home Assistant

Sorry if this is confusing.  Not sure of the right lingo to use.

**Comment by DigiH** [comment]
Hi @bouton,

while it will be unlikely, for the above mentioned reasons of most everyone with a Puck.js having their own applications on them, to include an official [Decoder](https://github.com/theengs/decoder) for use with OpenMQTTGateway, your iBeacon Bangle should already be detected and decoded as an iBeacon for presence detection.

For you individual Puck.js you could define your own decoder by following the [Theengs Decoder documentation](https://decoder.theengs.io/participate/adding-decoders.html) to include in an individual build for OpenMQTTGateway.

If you are actually looking to reduce your devices, you are using Home Assistant and you are mainly interested in Bluetooth device recognition, then [Theengs Gateway](https://github.com/theengs/gateway) might be the way to go for your use case - even more easily integrated in HA with the [Theengs Gateway Add-on](https://github.com/theengs/addon-theengsgw).

While it is impossible to include a generic Puck.js decoder, we are trying to implement more generally used standard Bluetooth SIG services/characteristics, which many devices use. So far this only includes the 0x180F/0x2A19 - battery level.

I hope this explains the situation a bit and help you in finding the most suitable solution for your use case.

**Comment by bouton** [comment]
Thanks. I looked into Theengs and was a bit overwhelmed. Will look again,
taking a deep breath.
As for Bluetooth SIG services/characteristics that seems an obvious
addition. Looking forward to all/some additions.

Thanks

**Comment by alfista2600** [comment]
getting back to my own puck.js as I have a particular use case. I've been able to send it commands over bluetooth using EspruinoHub/MQTT on a Pi Zero but I'd rather send it commands through an OMG device. Is this possible with a relatively little amount of effort?

**Comment by DigiH** [comment]
Hi @alfista2600 - [sending bluetooth commands via MQTT is already possible](https://docs.openmqttgateway.com/use/ble.html#read-write-ble-characteristics-over-mqtt) with OpenMQTTGateway, so you should also be able to send these through your OMG gateway, unless sending the commands requires a PIN, which is not yet implemented.

Hope this helps.
