### ISSUE TITLE
wifi_password setting has to be quoted when compiling in PlatformIO?

### ISSUE THREAD

**Issue by ilgrank** [1technophile/OpenMQTTGateway#1475]
Hi
I've just discovered that when compiling using PlatformIO, the wifi_password setting override has to be typed without quotes, ie:
`-Dwifi_password="password!"` <-Works
while
`'-Dwifi_password="password!"'` <-Does **not** work 

(I've also tried triple-backslash escaping the exclamation mark btw, not knowing which chars are considered special, but that did not change the observed behaviour)

Now, to be honest, in the [main docs ](https://docs.openmqttgateway.com/upload/builds.html#configure-upload-with-platformio) it is correctly listed _without_ single quotes, but elsewhere else in the code, it shows with quotes, e.g. in:
`environment.ini: Line  349: ;  '-Dwifi_password="WIFI_PASSWORD"'`
`prod_env.ini.example Line  76:   '-Dwifi_password="MyWiFiAPPassword"'`

is it a typo or I'm missing something? (eg: Why this is the only setting override that does not require to be single-quoted?)
Thanks!

**Comment by ilgrank** [comment]
closing as this is just a curiosity, and I've found there's 
https://community.openmqttgateway.com/
for discussion, sorry

**Comment by DigiH** [comment]
Hi @ilgrank, I've been using the quoted
`'-Dwifi_password="password!"'`
for ages - at least since version 0.9.3, so I am more perplexed to now see your stated doc examples without the single quotes, and hearing that you are having build issues with the fully quoted one.

Interested to hear what @1technophile has to say about this :)

**Comment by ilgrank** [comment]
To clarify: I'm not having build issues, it's just that if I do build with single quotes around the wifi_password parameter, it just **won't connect** to my AP and will start the wifi the captive portal, while if I do remove the single quotes, it does connect to my AP.

Also, when saying :
> in the [main docs ](https://docs.openmqttgateway.com/upload/builds.html#configure-upload-with-platformio)it is correctly listed without single quotes

...I'm referring to [https://docs.openmqttgateway.com/upload/builds.html#configure-upload-with-platformio](https://docs.openmqttgateway.com/upload/builds.html#configure-upload-with-platformio)  where the wifi_password override code is shown *without* single quotes

**Comment by DigiH** [comment]
> I'm referring to https://docs.openmqttgateway.com/upload/builds.html#configure-upload-with-platformio (also updated the original post with the docs link)

I know, that's what I meant that seeing this in the docs really puzzled me, as I've been using the fully quoted version for so long, without build issues or connection issues to my AP. Especially since I've only been using 

```
'-DESPWifiManualSetup=true'
'-Dwifi_ssid="mySSID"'
'-Dwifi_password="myPASSWORD"'
```
for so long on all my various OMG gateways. 

Just makes me wonder why the docs have this unquoted version, and how and why it is the only working version for you … and what the original peculiarity was for this.

**Comment by ilgrank** [comment]
I had not tried
'-DESPWifiManualSetup=true' 
before, so out of curiosity, using it with along with quoted wifi password  *does* work for me

**Comment by DigiH** [comment]
> '-DESPWifiManualSetup=true'

is required to correctly use the manual WiFi and MQTT credentials. So this was likely the issue.

The docs possibly need some adjustments though, with including `'-DESPWifiManualSetup=true' `and single quoted `'-Dwifi_password="myPASSWORD"',` unless, I am wondering, the unquoted version has something to do with the escaped characters in the example?!?

**Comment by DigiH** [comment]
FYI - https://github.com/1technophile/OpenMQTTGateway/pull/1476

Thanks for pointing this out.

**Comment by ilgrank** [comment]
Thanks for opening the issue :)
