### ISSUE TITLE
FR: Adding some security fields to the webui

### ISSUE THREAD

**Issue by neoatomic** [1technophile/OpenMQTTGateway#1752]
Would it be possible to extend the WebUI to configure:

A field for custom SSID of the fallback AP
A field for custom password for the fallback AP
A field for custom MAC address for the device
A field for custom device name
Remove the option to show a password in the webUI
Completely disable fallback AP after setup (usb reflash only)

Those would be for security reasons. 

Description:

I'm currently using the pre-build firmware for convenience, and in the process of thinking how to best secure the devices.

When the fallback AP kicks in, anyone who does a quick google search can find (from the ssid) that its a OMG device and what the default login/password is. Currently with a pre-build firmware the fallback AP ssid/login/password cant be changed. So it would be relatively easy to access the device in that situation. Once an unauthorized person has access, he can also see the main AP password where the device connects to by simply clicking on show password. And a custom MAC address would be useful to mask that its a ESP device (that generally has lesser security) so an attacker might not target it in the first place.

Those settings are available if you custom build, so hopefully its possible to access them in the webui. Another positive is that it might reduce the need of a group of users to custom build completely.

**Comment by pauln** [comment]
It'd also be nice to be able to change the OTA password (especially since it's also the web UI password) via the web UI.  If you miss changing it during initial wifi configuration (or just want to change it later), there doesn't currently seem to be a way to change it short of wiping the config or preventing it from connecting to your network in some way (to get back to the captive portal) - though please let me know if I've missed something.
