### ISSUE TITLE
Add support for Auriol LD6654

### ISSUE THREAD

**Issue by DeckardCain2014** [1technophile/OpenMQTTGateway#2099]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to know if it would be possible to add the Auriol LD6654 weather station support.

**Describe the solution you'd like**
Auriol LD6654 weather station support.

**Describe alternatives you've considered**
Flashed the Lilygo RTL 433 firmware and connected to MQTT. However, my weather station is not discovered.

**Additional context**
--

**Comment by NorthernMan54** [comment]
Is it supported by rtl_433?

**Comment by DeckardCain2014** [comment]
I don't know, is there a list? Is it a prerequisite for the open mqtt gateway?

**Comment by DigiH** [comment]
While there are several Auriol devices supported by rtl_433, your LD6654 weather station does not seem to be included yet

https://github.com/merbanan/rtl_433?tab=readme-ov-file#running

It's not a typo by any chance above, as an -LD5664 is supported? 😉

**Comment by DeckardCain2014** [comment]
Basically it's a 4-LD5564 😁

**Comment by DigiH** [comment]
So the LD5664 is supported by rtl)433, but disabled by default, as you might have seen on the above linked page, due to

https://github.com/merbanan/rtl_433/blob/master/src/devices/auriol_4ld5661.c#L107 

That might also be the reason why @NorthernMan54 has not ported this particular decoder over to rtl_433_ESP (yet)?!?

**Comment by DeckardCain2014** [comment]
Actually it is a 4-LD5564, not a 5664 :D So it might be not at all supported. I think I will return it then...
